apiVersion: v1
kind: Pod
metadata:
  name: cap03-multicontenedor
spec:
  containers:
    - name: nginx # Primer contenedor
      image: nginx:stable-alpine
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html # Monta el volumen (html) en /usr/share/nginx/html
      ports:
        - containerPort: 80
    - name: logger # Segundo contenedor
      image: alpine:latest
      command: ["/bin/sh", "-c"] # Ejecutamos en el contenedor lo que hay en "args"
      args:
        - while true; do
          date >> /html/index.html;
          sleep 5;
          done
      volumeMounts:
        - name: html
          mountPath: /html
  volumes: # Volumen creado
    - name: html
      emptyDir: {} # Volumen efímero vacío
